### ISSUE TITLE
Experimental and original won't build on clang 9.0.0

### ISSUE THREAD

**Issue by rilerez** [skypjack/entt#281]
I'm running on arch linux. GCC works fine. 

I get errors about `family::family` type. Specifically,

     [ 18%] Building CXX object test/CMakeFiles/dispatcher.dir/entt/signal/dispatcher.cpp.o
    In file included from /home/riley/projects/entt-original/test/entt/signal/dispatcher.cpp:4:
    In file included from /home/riley/projects/entt-original/src/entt/signal/dispatcher.hpp:10:
    /home/riley/projects/entt-original/src/entt/signal/../core/family.hpp:33:37: error: cannot initialize a variable of
          type 'const entt::family::family_type' (aka 'const unsigned int') with an lvalue of type 'const auto'
        inline static const family_type type = inner<std::decay_t<Type>...>;
                                        ^      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /home/riley/projects/entt-original/src/entt/signal/dispatcher.hpp:86:34: note: in instantiation of static data member
          'entt::family<entt::internal_dispatcher_event_family>::type<one_more_event>' requested here
                return event_family::type<Event>;
                                     ^
    /home/riley/projects/entt-original/src/entt/signal/dispatcher.hpp:92:28: note: in instantiation of function template
          specialization 'entt::dispatcher::type<one_more_event>' requested here
            const auto wtype = type<Event>();
                               ^
    /home/riley/projects/entt-original/src/entt/signal/dispatcher.hpp:162:9: note: in instantiation of function template
          specialization 'entt::dispatcher::assure<one_more_event>' requested here
            assure<Event>().trigger(std::forward<Args>(args)...);
            ^
    /home/riley/projects/entt-original/test/entt/signal/dispatcher.cpp:22:16: note: in instantiation of function template
          specialization 'entt::dispatcher::trigger<one_more_event>' requested here
        dispatcher.trigger<one_more_event>();
                   ^
    In file included from /home/riley/projects/entt-original/test/entt/signal/dispatcher.cpp:4:
    In file included from /home/riley/projects/entt-original/src/entt/signal/dispatcher.hpp:10:
    /home/riley/projects/entt-original/src/entt/signal/../core/family.hpp:33:37: error: cannot initialize a variable of
          type 'const entt::family::family_type' (aka 'const unsigned int') with an lvalue of type 'const auto'
        inline static const family_type type = inner<std::decay_t<Type>...>;
                                        ^      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /home/riley/projects/entt-original/src/entt/signal/dispatcher.hpp:86:34: note: in instantiation of static data member
          'entt::family<entt::internal_dispatcher_event_family>::type<another_event>' requested here
                return event_family::type<Event>;
                                     ^
    /home/riley/projects/entt-original/src/entt/signal/dispatcher.hpp:92:28: note: in instantiation of function template
          specialization 'entt::dispatcher::type<another_event>' requested here
            const auto wtype = type<Event>();
                               ^
    /home/riley/projects/entt-original/src/entt/signal/dispatcher.hpp:191:9: note: in instantiation of function template
          specialization 'entt::dispatcher::assure<another_event>' requested here
            assure<Event>().enqueue(std::forward<Args>(args)...);
            ^
    /home/riley/projects/entt-original/test/entt/signal/dispatcher.cpp:32:16: note: in instantiation of function template
          specialization 'entt::dispatcher::enqueue<another_event>' requested here
        dispatcher.enqueue<another_event>();
                   ^
    2 errors generated.

**Comment by Kerndog73** [comment]
Does replacing `auto` with `ENTT_ID_TYPE` fix the problem?

**Comment by rilerez** [comment]
Yep that fixed it! Does this seem like a clang bug?

**Comment by Kerndog73** [comment]
@rilerez Yeah, seems like a clang bug.

**Comment by skypjack** [comment]
What version of clang are you using? The CI runs clang 6 with no errors while I'm using the latest version during development.

**Comment by rilerez** [comment]
Only core/family.hpp needs to be changed

[clang9_family_patch.txt](https://github.com/skypjack/entt/files/3483721/clang9_family_patch.txt)

**Comment by skypjack** [comment]
Thank you for testing this. Really appreciated.
