### ISSUE TITLE
using basic_registry<uint64_t> on MSVC

### ISSUE THREAD

**Issue by davidc538** [skypjack/entt#1174]
I have tested this code and it works on clang 15+ and gcc 13+ but not MSVC. I'm using VS2022 with platform:x64, platform toolset v143 and /std:c++20. Using entt::entity and uint32_t both work fine, I would like the ability to use uint64_t though. Can you help?

```
#include <iostream>
#include <cstdint>
#include <entt/entt.hpp>

//using Ent = entt::entity;
using Entity = uint64_t;
//using Ent = uint32_t;
using Registry = entt::basic_registry<Entity>;

struct TestData {
	int age;
	TestData(int age) : age(age) { }
};

int main() {
	Registry reg;
	for (int i = 0; i < 10; i++) {
		Entity ent = reg.create();
		TestData& data = reg.emplace<TestData>(ent, 1);
	}

	// these lines cause compile errors on MSVC with `using Entity = uint64_t`,
	// entt::entity and uint32_t work fine
	auto view = reg.view<TestData>();
	for (Entity ent : view) {
		TestData& data = view.get<TestData>(ent);
		std::cout << data.age << std::endl;
	}
	// end of compile errors section
}
```
Results in the following compiler errors...
```
Build started at 8:46 AM...
1>------ Build started: Project: vkf, Configuration: Release x64 ------
1>EnttMCVE.cpp
1>C:\SDK\vcpkg\installed\x64-windows\include\entt\entity\view.hpp(863,75): error C2556: 'unsigned __int64 entt::basic_view<entt::get_t<entt::basic_sigh_mixin<entt::basic_storage<Type,Entity,Allocator,void>,entt::basic_registry<Entity,std::allocator<size_t>>>>,entt::exclude_t<>,void>::operator [](const unsigned __int64) const': overloaded function differs only by return type from 'decltype(auto) entt::basic_view<entt::get_t<entt::basic_sigh_mixin<entt::basic_storage<Type,Entity,Allocator,void>,entt::basic_registry<Entity,std::allocator<size_t>>>>,entt::exclude_t<>,void>::operator [](const unsigned __int64) const'
1>C:\SDK\vcpkg\installed\x64-windows\include\entt\entity\view.hpp(863,75): error C2556:         with
1>C:\SDK\vcpkg\installed\x64-windows\include\entt\entity\view.hpp(863,75): error C2556:         [
1>C:\SDK\vcpkg\installed\x64-windows\include\entt\entity\view.hpp(863,75): error C2556:             Type=TestData,
1>C:\SDK\vcpkg\installed\x64-windows\include\entt\entity\view.hpp(863,75): error C2556:             Entity=Entity,
1>C:\SDK\vcpkg\installed\x64-windows\include\entt\entity\view.hpp(863,75): error C2556:             Allocator=std::allocator<TestData>
1>C:\SDK\vcpkg\installed\x64-windows\include\entt\entity\view.hpp(863,75): error C2556:         ]
1>(compiling source file '../../tests/EnttMCVE.cpp')
1>    C:\SDK\vcpkg\installed\x64-windows\include\entt\entity\view.hpp(854,34):
1>    see declaration of 'entt::basic_view<entt::get_t<entt::basic_sigh_mixin<entt::basic_storage<Type,Entity,Allocator,void>,entt::basic_registry<Entity,std::allocator<size_t>>>>,entt::exclude_t<>,void>::operator []'
1>        with
1>        [
1>            Type=TestData,
1>            Entity=Entity,
1>            Allocator=std::allocator<TestData>
1>        ]
1>    C:\SDK\vcpkg\installed\x64-windows\include\entt\entity\view.hpp(863,75):
1>    the template instantiation context (the oldest one first) is
1>        C:\SDK\vkf\tests\EnttMCVE.cpp(28,18):
1>        see reference to class template instantiation 'entt::basic_view<entt::get_t<entt::basic_sigh_mixin<entt::basic_storage<Type,Entity,Allocator,void>,entt::basic_registry<Entity,std::allocator<size_t>>>>,entt::exclude_t<>,void>' being compiled
1>        with
1>        [
1>            Type=TestData,
1>            Entity=Entity,
1>            Allocator=std::allocator<TestData>
1>        ]
1>C:\SDK\vcpkg\installed\x64-windows\include\entt\entity\view.hpp(863,75): error C2371: 'entt::basic_view<entt::get_t<entt::basic_sigh_mixin<entt::basic_storage<Type,Entity,Allocator,void>,entt::basic_registry<Entity,std::allocator<size_t>>>>,entt::exclude_t<>,void>::operator []': redefinition; different basic types
1>C:\SDK\vcpkg\installed\x64-windows\include\entt\entity\view.hpp(863,75): error C2371:         with
1>C:\SDK\vcpkg\installed\x64-windows\include\entt\entity\view.hpp(863,75): error C2371:         [
1>C:\SDK\vcpkg\installed\x64-windows\include\entt\entity\view.hpp(863,75): error C2371:             Type=TestData,
1>C:\SDK\vcpkg\installed\x64-windows\include\entt\entity\view.hpp(863,75): error C2371:             Entity=Entity,
1>C:\SDK\vcpkg\installed\x64-windows\include\entt\entity\view.hpp(863,75): error C2371:             Allocator=std::allocator<TestData>
1>C:\SDK\vcpkg\installed\x64-windows\include\entt\entity\view.hpp(863,75): error C2371:         ]
1>(compiling source file '../../tests/EnttMCVE.cpp')
1>    C:\SDK\vcpkg\installed\x64-windows\include\entt\entity\view.hpp(854,34):
1>    see declaration of 'entt::basic_view<entt::get_t<entt::basic_sigh_mixin<entt::basic_storage<Type,Entity,Allocator,void>,entt::basic_registry<Entity,std::allocator<size_t>>>>,entt::exclude_t<>,void>::operator []'
1>        with
1>        [
1>            Type=TestData,
1>            Entity=Entity,
1>            Allocator=std::allocator<TestData>
1>        ]
1>C:\SDK\vcpkg\installed\x64-windows\include\entt\entity\view.hpp(864,9): error C2059: syntax error: 'return'
1>(compiling source file '../../tests/EnttMCVE.cpp')
1>C:\SDK\vcpkg\installed\x64-windows\include\entt\entity\view.hpp(864,39): error C2238: unexpected token(s) preceding ';'
1>(compiling source file '../../tests/EnttMCVE.cpp')
1>C:\SDK\vcpkg\installed\x64-windows\include\entt\entity\view.hpp(873,5): error C2143: syntax error: missing ';' before '<L_GRAMMAR_template_head_l>'
1>(compiling source file '../../tests/EnttMCVE.cpp')
1>C:\SDK\vkf\tests\EnttMCVE.cpp(30,25): error C2039: 'get': is not a member of 'entt::basic_view<entt::get_t<entt::basic_sigh_mixin<entt::basic_storage<Type,Entity,Allocator,void>,entt::basic_registry<Entity,std::allocator<size_t>>>>,entt::exclude_t<>,void>'
1>C:\SDK\vkf\tests\EnttMCVE.cpp(30,25): error C2039:         with
1>C:\SDK\vkf\tests\EnttMCVE.cpp(30,25): error C2039:         [
1>C:\SDK\vkf\tests\EnttMCVE.cpp(30,25): error C2039:             Type=TestData,
1>C:\SDK\vkf\tests\EnttMCVE.cpp(30,25): error C2039:             Entity=Entity,
1>C:\SDK\vkf\tests\EnttMCVE.cpp(30,25): error C2039:             Allocator=std::allocator<TestData>
1>C:\SDK\vkf\tests\EnttMCVE.cpp(30,25): error C2039:         ]
1>    C:\SDK\vcpkg\installed\x64-windows\include\entt\entity\view.hpp(772,7):
1>    see declaration of 'entt::basic_view<entt::get_t<entt::basic_sigh_mixin<entt::basic_storage<Type,Entity,Allocator,void>,entt::basic_registry<Entity,std::allocator<size_t>>>>,entt::exclude_t<>,void>'
1>        with
1>        [
1>            Type=TestData,
1>            Entity=Entity,
1>            Allocator=std::allocator<TestData>
1>        ]
1>C:\SDK\vkf\tests\EnttMCVE.cpp(30,18): error C2530: 'data': references must be initialized
1>Done building project "vkf.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
========== Build completed at 8:46 AM and took 01.504 seconds ==========
```

**Comment by skypjack** [comment]
Cannot reproduce the error locally with the configuration above (VS2022, toolset v143, C++20). Something else that you forgot to mention? The snippet compiles just fine here and it's hard to help if I can't make it fail. 🤔

**Comment by davidc538** [comment]
I am using the one from vcpkg tag: `2024.08.23` but it didn't work on the previous tag either `2024.07.12`. Apart from that, I don't know what details might be relevant.

**Comment by Innokentiy-Alaytsev** [comment]
Are you using `experimental` branch?

**Comment by davidc538** [comment]
> Are you using `experimental` branch?

I'm not sure what you're referring to but I don't believe so.

**Comment by Innokentiy-Alaytsev** [comment]
The fix is "simple": the deprecated overload should be removed entirely. Another option would be using strong `typedef`s of some sort, but that should be done from the beginning.

**Comment by davidc538** [comment]
I don't have the same version of the file that you linked, although I was able to get my project to compile by commenting out the first subscript operator...
```
//[[nodiscard]] entity_type operator[](const size_type pos) const {
//    return begin()[pos];
//}
```

**Comment by davidc538** [comment]
> The fix is "simple": the deprecated overload should be removed entirely. Another option would be using strong `typedef`s of some sort, but that should be done from the beginning.

do you mean that this should be done in user code or in entt?

**Comment by Innokentiy-Alaytsev** [comment]
I believe, it should be done in EnTT. At very least, all occurrences of using the deprecated version of the `operator[]` should be replaced inside EnTT. Potentially, the subscript operators should be reworked into properly named functions.

**Comment by davidc538** [comment]
I'm sorry, I posted commented out code from the wrong file. Here is the correction...

taken from entt\entity\view.hpp:854
```
    //[[nodiscard]] decltype(auto) operator[](const entity_type entt) const {
    //    return storage()->get(entt);
    //}
```

Any idea why this would compile with clang and gcc though? that is strange to me...

**Comment by Innokentiy-Alaytsev** [comment]
From what I know, Clang and GCC process templates differently compared to MSVC. The error might appear there under other circumstances. But there might be some other reason which is beyond me.

**Comment by skypjack** [comment]
Hold on. I double checked your snippet. As from the [documentation](https://github.com/skypjack/entt/wiki/Entity-Component-System#the-registry-the-entity-and-the-component):

> User defined identifiers are allowed as enum classes and class types that define an entity_type member of type std::uint32_t or std::uint64_t.

It means that you have at least to do this:

```cpp
enum class Entity : uint64_t {};
```

If this triggers the same error, then there is something to fix. Otherwise, it works as expected. Let me know. Thanks. 👍

**Comment by davidc538** [comment]
> ```c++
> enum class Entity : uint64_t {};
> ```

This actually explains alot, thanks. I wish I understood how the code was working on GCC and Clang though.

**Comment by skypjack** [comment]
I guess the above explanation solved the issue. Feel free to reopen it if this isn't the case. 👍

**Comment by davidc538** [comment]
Yes, it is solved. thanks for your help! I plan to investigate what clang and gcc are doing the next time I boot up on linux, maybe overload resolution is UB when `entity_type` isn't an enum? [suggestion](https://en.cppreference.com/w/cpp/types/is_enum)
