### ISSUE TITLE
view fails with const modifier and exclude types.

### ISSUE THREAD

**Issue by pgruenbacher** [skypjack/entt#507]
compilation issue with EnTT master
``` EntityType getActiveCamera(const Registry& registry, int viewId) {

  const auto view2 = registry.view<const int, const char>(entt::exclude<float>);

```
 ```/home/pgruenbacher/Code/cpp/entrender/thirdparty/EnTT/src/entt/entity/registry.hpp:1314:77: error: binding reference of type ‘entt::basic_view<entt::entity, entt::exclude_t<float>, int, char>::pool_type<int>&’ {aka ‘entt::storage<entt::entity, int, void>&’} to ‘const entt::storage<entt::entity, int, void>’ discards qualifiers
         return { assure<std::decay_t<Component>>()..., assure<Exclude>()... };
```
so entt::exclude pool type float is failing because of const modifier, but not sure how to fix...
can't make entt::exclude<const float> because that will fail when Component != decay_t<Component>

**Comment by skypjack** [comment]
Not sure I get what the problem is. Are you saying that you can't use `const float` with `entt::xclude` or that the call to `view` above doesn't work?

**Comment by pgruenbacher** [comment]
the view has compile error. I think it's inherent to const registry calling
view() with an exclude argument(s)

**Comment by pgruenbacher** [comment]
this demonstrates the issue
https://github.com/skypjack/entt/compare/master...pgruenbacher:patch-4

maybe need a std::add_const or std::remove_const somewhere on Exclude type but not sure what the fix is

**Comment by skypjack** [comment]
Ok ok, I didn't get what was the problem, sorry.
Did you try also v3.4? Is this only on `master`?
I made a change, probably I know what caused this.

**Comment by pgruenbacher** [comment]
this is on master. also fails to compile on v3.4.0 I think.

my point is that calling view() from const registry with an exclude type argument fails to compile.

**Comment by skypjack** [comment]
It should work on `experimental`.
The branch doesn't compile with GCC7 because of a bug of the compiler (I'm looking into it right away) but passed all other tests.
Thanks for pointing this out. Let me know if it doesn't solve. :+1:
