### ISSUE TITLE
Entt 2.7.3 compile error on VS 2017 Community

### ISSUE THREAD

**Issue by vendik** [skypjack/entt#168]
Compiling this code on VS 2017 Community, using 2.7.3 entt release:

```
#include <entt/entt.hpp>

struct ComponentA {};
struct ComponentB {};

int main() {
    entt::DefaultRegistry registry;
    auto view = registry.view<ComponentA>();
    for (auto entity : view) {
        const ComponentA& labelComp = view.get<ComponentA>(entity);
    }
    return EXIT_SUCCESS;
}
```

Gives me a compilation error:
```
Main.cpp(10): error C2275: 'ComponentA': illegal use of this type as an expression
```

But if I replace 
`auto view = registry.view<ComponentA>();` line with 
`auto view = registry.view<ComponentA, ComponentB>();`
everything works fine.

What could the issue be?

**Comment by vblanco20-1** [comment]
@vendik  single component views dont need to have the <Component> in the get function.
it works like this
```
  for (auto entity : view) {
        const ComponentA& labelComp = view.get(entity);
    }
```

**Comment by skypjack** [comment]
To be honest, I don't know. I didn't even manage to reproduce it actually.  
Btw appveyor keeps saying that VS2017 works fine with `v2.3.0` and it's compiling much more complex examples.

A fast search with Google gave me a lot of things to look into and solve the issue. Almost all are related to VS and the way people compiles their sources.

**Comment by skypjack** [comment]
@vendik 

@vblanco20-1 pointed out the right problem. I'm closing the issue. 
Do not forget to star the project if you like it and feel free to ping me if you want to add your project to the section _EnTT in Action_ of the wiki.
